[package]
name = "blackhole"
version = "0.1.0"
edition = "2018"
authors = ["rishflab"]

[features]
default = []
metal = ["gfx-backend-metal"]
dx12 = ["gfx-backend-dx12"]
vulkan = ["gfx-backend-vulkan"]


[dependencies]
specs =  "0.14"
shrev = "1.0.1"
rhusics-ecs = {git = "https://github.com/rustgd/rhusics.git"}
rhusics-core = {git = "https://github.com/rustgd/rhusics.git"}
cgmath = "0.16"
collision = "0.18.0"
smallvec = "0.6.5"
bincode = "*"
serde_derive = "*"
serde = "*"
gfx-hal = "0.1"
log = "0.4.0"
simple_logger = "1.0"
winit = "0.18"
arrayvec = "0.4"
shaderc = "0.3"
image = "0.21"
nalgebra-glm = "0.2"
rand = "0.6"


[dependencies.gfx-backend-vulkan]
version = "0.1"
optional = true

[target.'cfg(target_os = "macos")'.dependencies.gfx-backend-metal]
version = "0.1"
optional = true

[target.'cfg(windows)'.dependencies.gfx-backend-dx12]
version = "0.1"
optional = true

[[bin]]
name = "send_rpc"
path = "src/bin/utils/send_rpc.rs"

[[bin]]
name = "rpc_server"
path = "src/bin/rpc_server.rs"


