[package]
name = "teleport"
version = "0.1.0"
authors = ["rishflab"]

[dependencies]
specs =  "0.12.0"
shrev = "1.0.1"
rhusics-ecs = {git = "https://github.com/rustgd/rhusics.git"}
rhusics-core = {git = "https://github.com/rustgd/rhusics.git"}
cgmath = "0.16"
collision = "0.18.0"
smallvec = "0.6.5"
bincode = "*"
serde_derive = "*"
serde = "*"

[examples]


[[bin]]
name = "send_rpc"
path = "src/bin/utils/send_rpc.rs"

[[bin]]
name = "rpc_server"
path = "src/bin/rpc_server.rs"

